#!/usr/bin/env python3
"""Generate the Codex copies of the crew from their single source in .claude/.

Sources (edit these, never the copies):
  .claude/agents/<slug>.md          -> .codex/agents/<slug>.toml
  .claude/skills/<name>/SKILL.md    -> .agents/skills/<name>/SKILL.md

Usage:
  python tools/sync_codex.py           write the copies
  python tools/sync_codex.py --check   exit 1 if any copy is stale (for CI)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTS_SRC = ROOT / ".claude" / "agents"
SKILLS_SRC = ROOT / ".claude" / "skills"
AGENTS_OUT = ROOT / ".codex" / "agents"
SKILLS_OUT = ROOT / ".agents" / "skills"

BANNER = "# Generated by tools/sync_codex.py from .claude/agents/{slug}.md. Do not edit; edit the source and re-run.\n"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def split_frontmatter(text: str, path: Path):
    m = re.match(r"---\n(.*?)\n---\n(.*)\Z", text, re.S)
    if not m:
        raise SystemExit(f"{path}: no frontmatter")
    fields = {}
    for line in m.group(1).split("\n"):
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields, m.group(2).strip("\n")


def agent_toml(path: Path) -> str:
    fields, body = split_frontmatter(read(path), path)
    for key in ("name", "description"):
        if not fields.get(key):
            raise SystemExit(f"{path}: missing '{key}'")
    if "'''" in body:
        raise SystemExit(f"{path}: body contains ''' which the TOML literal string cannot hold")
    return (BANNER.format(slug=path.stem)
            + f"name = {json.dumps(fields['name'], ensure_ascii=False)}\n"
            + f"description = {json.dumps(fields['description'], ensure_ascii=False)}\n"
            + f"developer_instructions = '''\n{body}\n'''\n")


def expected() -> dict[Path, str]:
    out: dict[Path, str] = {}
    for src in sorted(AGENTS_SRC.glob("*.md")):
        # A role file has frontmatter; anything else in this folder is not an agent.
        if read(src).startswith("---\n"):
            out[AGENTS_OUT / f"{src.stem}.toml"] = agent_toml(src)
    for src in sorted(SKILLS_SRC.glob("*/SKILL.md")):
        out[SKILLS_OUT / src.parent.name / "SKILL.md"] = read(src)
    return out


def existing() -> set[Path]:
    return set(AGENTS_OUT.glob("*.toml")) | set(SKILLS_OUT.glob("*/SKILL.md"))


def main() -> int:
    want = expected()
    stale = []
    for path, content in want.items():
        current = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else None
        if current != content:
            stale.append(path)
    orphans = sorted(existing() - set(want))
    if "--check" in sys.argv:
        for p in stale:
            print(f"stale: {p.relative_to(ROOT)}")
        for p in orphans:
            print(f"orphan: {p.relative_to(ROOT)}")
        if stale or orphans:
            print("Run: python tools/sync_codex.py")
            return 1
        print(f"{len(want)} Codex copies up to date")
        return 0
    for path in stale:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(want[path], encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    for path in orphans:
        path.unlink()
        print(f"removed {path.relative_to(ROOT)}")
    print(f"{len(want)} Codex copies up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
